### ISSUE TITLE
edit button might be unnecessary

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#157]
On http://localhost:8000/policy/show/1, I note that each rule has an edit form underneath it but then also includes an 'edit' button, but these 'edit' buttons all just lead back to http://localhost:8000/policy/show/1. So are they needed here?

**Comment by ablwr** [comment]
I don't see this, but then I realized that for whatever reason, and to go along with ticket #156, I think there is something wrong with the way your signalserver is compiling because it's showing things that would normally be hidden until clicked. So same with #156 -- you should not see an edit form underneath all the rules, you should only see the edit button. And clicking the edit button opens up the edit form.

**Comment by ablwr** [comment]
So under expected circumstances it is necessary cuz the form is hidden!

**Comment by ablwr** [comment]
I am going to close this... because this has to do with assets not compiling properly, a different issue.
